---
- name: Install and configure MySQL
  hosts: webservers
  become: yes
  remote_user: root
  vars_files:
    - ../vars/mysql.yaml
  pre_tasks:
    - name: installing python-3 mysql libraries
      apt: name=python3-mysqldb state=present
  roles:
    - geerlingguy.mysql
